/* Auto-generated by genmsg_cpp for file /home/andrewsy/ros/starmac-ros-pkg/starmac_vicon/vicon_mocap/msg/Markers.msg */
#ifndef VICON_MOCAP_MESSAGE_MARKERS_H
#define VICON_MOCAP_MESSAGE_MARKERS_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "std_msgs/Header.h"
#include "vicon_mocap/Marker.h"

namespace vicon_mocap
{
template <class ContainerAllocator>
struct Markers_ : public ros::Message
{
  typedef Markers_<ContainerAllocator> Type;

  Markers_()
  : header()
  , frame_number(0)
  , markers()
  {
  }

  Markers_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , frame_number(0)
  , markers(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef uint32_t _frame_number_type;
  uint32_t frame_number;

  typedef std::vector< ::vicon_mocap::Marker_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::vicon_mocap::Marker_<ContainerAllocator> >::other >  _markers_type;
  std::vector< ::vicon_mocap::Marker_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::vicon_mocap::Marker_<ContainerAllocator> >::other >  markers;


  ROS_DEPRECATED uint32_t get_markers_size() const { return (uint32_t)markers.size(); }
  ROS_DEPRECATED void set_markers_size(uint32_t size) { markers.resize((size_t)size); }
  ROS_DEPRECATED void get_markers_vec(std::vector< ::vicon_mocap::Marker_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::vicon_mocap::Marker_<ContainerAllocator> >::other > & vec) const { vec = this->markers; }
  ROS_DEPRECATED void set_markers_vec(const std::vector< ::vicon_mocap::Marker_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::vicon_mocap::Marker_<ContainerAllocator> >::other > & vec) { this->markers = vec; }
private:
  static const char* __s_getDataType_() { return "vicon_mocap/Markers"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "579f0637989aa8139ce6bf98cf7aabda"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header header\n\
uint32 frame_number # Vicon Frame Number\n\
vicon_mocap/Marker[] markers # Array of Markers\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: vicon_mocap/Marker\n\
string marker_name\n\
string subject_name\n\
string segment_name\n\
geometry_msgs/Point translation\n\
bool occluded\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, frame_number);
    ros::serialization::serialize(stream, markers);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, frame_number);
    ros::serialization::deserialize(stream, markers);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(frame_number);
    size += ros::serialization::serializationLength(markers);
    return size;
  }

  typedef boost::shared_ptr< ::vicon_mocap::Markers_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vicon_mocap::Markers_<ContainerAllocator>  const> ConstPtr;
}; // struct Markers
typedef  ::vicon_mocap::Markers_<std::allocator<void> > Markers;

typedef boost::shared_ptr< ::vicon_mocap::Markers> MarkersPtr;
typedef boost::shared_ptr< ::vicon_mocap::Markers const> MarkersConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::vicon_mocap::Markers_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::vicon_mocap::Markers_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace vicon_mocap

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::vicon_mocap::Markers_<ContainerAllocator> > {
  static const char* value() 
  {
    return "579f0637989aa8139ce6bf98cf7aabda";
  }

  static const char* value(const  ::vicon_mocap::Markers_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x579f0637989aa813ULL;
  static const uint64_t static_value2 = 0x9ce6bf98cf7aabdaULL;
};

template<class ContainerAllocator>
struct DataType< ::vicon_mocap::Markers_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vicon_mocap/Markers";
  }

  static const char* value(const  ::vicon_mocap::Markers_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::vicon_mocap::Markers_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
uint32 frame_number # Vicon Frame Number\n\
vicon_mocap/Marker[] markers # Array of Markers\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: vicon_mocap/Marker\n\
string marker_name\n\
string subject_name\n\
string segment_name\n\
geometry_msgs/Point translation\n\
bool occluded\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
";
  }

  static const char* value(const  ::vicon_mocap::Markers_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::vicon_mocap::Markers_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::vicon_mocap::Markers_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::vicon_mocap::Markers_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.frame_number);
    stream.next(m.markers);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Markers_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vicon_mocap::Markers_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::vicon_mocap::Markers_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "frame_number: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.frame_number);
    s << indent << "markers[]" << std::endl;
    for (size_t i = 0; i < v.markers.size(); ++i)
    {
      s << indent << "  markers[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::vicon_mocap::Marker_<ContainerAllocator> >::stream(s, indent + "    ", v.markers[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // VICON_MOCAP_MESSAGE_MARKERS_H

