(cl:defpackage flyer_controller-srv
  (:use )
  (:export
   "GETAUTOSEQUENCE"
   "<GETAUTOSEQUENCE-REQUEST>"
   "GETAUTOSEQUENCE-REQUEST"
   "<GETAUTOSEQUENCE-RESPONSE>"
   "GETAUTOSEQUENCE-RESPONSE"
   "CONTROL_MODES"
   "<CONTROL_MODES-REQUEST>"
   "CONTROL_MODES-REQUEST"
   "<CONTROL_MODES-RESPONSE>"
   "CONTROL_MODES-RESPONSE"
  ))

