(cl:defpackage flyer_controller-msg
  (:use )
  (:export
   "<CONTROL_MODE_AUTOSEQUENCE_INFO>"
   "CONTROL_MODE_AUTOSEQUENCE_INFO"
   "<CONTROL_MODE_OUTPUT>"
   "CONTROL_MODE_OUTPUT"
   "<AUTOSEQUENCE>"
   "AUTOSEQUENCE"
   "<CONTROL_MODE_CMD>"
   "CONTROL_MODE_CMD"
   "<CONTROLLER_STATUS>"
   "CONTROLLER_STATUS"
   "<CONTROL_MODE_STATUS>"
   "CONTROL_MODE_STATUS"
   "<CONTROLLER_CMD>"
   "CONTROLLER_CMD"
   "<CONTROL_MODE_HOVER_INFO>"
   "CONTROL_MODE_HOVER_INFO"
   "<HOVERPOINT>"
   "HOVERPOINT"
   "<AUTOSEQUENCEPOINT>"
   "AUTOSEQUENCEPOINT"
  ))

