"""autogenerated by genmsg_py from HoverPoint.msg. Do not edit."""
import roslib.message
import struct


class HoverPoint(roslib.message.Message):
  _md5sum = "08bfd1a92b1f014382750e5b743b63a9"
  _type = "flyer_controller/HoverPoint"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """string name
float64 x # [m] (North)
float64 y # [m] (East)
float64 alt # [m]
float64 yaw # [deg]
float64 vx # [m/s]
float64 vy # [m/s]
"""
  __slots__ = ['name','x','y','alt','yaw','vx','vy']
  _slot_types = ['string','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       name,x,y,alt,yaw,vx,vy
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(HoverPoint, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.name is None:
        self.name = ''
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.alt is None:
        self.alt = 0.
      if self.yaw is None:
        self.yaw = 0.
      if self.vx is None:
        self.vx = 0.
      if self.vy is None:
        self.vy = 0.
    else:
      self.name = ''
      self.x = 0.
      self.y = 0.
      self.alt = 0.
      self.yaw = 0.
      self.vx = 0.
      self.vy = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self.name
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_6d.pack(_x.x, _x.y, _x.alt, _x.yaw, _x.vx, _x.vy))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.name = str[start:end]
      _x = self
      start = end
      end += 48
      (_x.x, _x.y, _x.alt, _x.yaw, _x.vx, _x.vy,) = _struct_6d.unpack(str[start:end])
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self.name
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_6d.pack(_x.x, _x.y, _x.alt, _x.yaw, _x.vx, _x.vy))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.name = str[start:end]
      _x = self
      start = end
      end += 48
      (_x.x, _x.y, _x.alt, _x.yaw, _x.vx, _x.vy,) = _struct_6d.unpack(str[start:end])
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_6d = struct.Struct("<6d")
